name: PHP CodeSniffer

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  phpcs:
    name: Run PHP_CodeSniffer
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: cs2pr

      - name: Require WordPress Coding Standards
        run: |
          composer global config allow-plugins.dealerdirect/phpcodesniffer-composer-installer true
          composer global require "wp-coding-standards/wpcs:^3.0"

      - name: Run PHPCS
        run: $(composer global config bin-dir --absolute)/phpcs --standard=phpcs.xml.dist --report=checkstyle | cs2pr
